---
image:
  repository: ghcr.io/podnebnik/website

ingressroute:
  enabled: true
  rule: Host(`stage.podnebnik.org`)
  certResolver: letsencrypt

persistence:
  existingClaim: website

existingSecret: website

fullnameOverride: website
