name: Deploy to GitHub pages

on:
  push:
    branches:
      - eleventy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - run: npm install -g yarn

      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the website
        run: yarn build

      - name: Init new repo commit generated files
        run: |
          cd dist
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Push to the destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: dist
